apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    - containerPort: 443
    volumeMounts:
    - name: conf-volume
      mountPath: /etc/nginx/conf.d
    - name: certs-volume
      mountPath: /etc/nginx/ssl
  volumes:
  - name: conf-volume
    hostPath:
      path: /root/nginx/conf
      type: DirectoryOrCreate
  - name: certs-volume
    hostPath:
      path: /root/nginx/certs
      type: DirectoryOrCreate