apiVersion: v1
kind: ConfigMap
metadata:
  name: data-volume
data:
  # Add your data here as key-value pairs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: letsencrypt-volume
data:
  # Add your data here as key-value pairs
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-proxy-manager
spec:
  containers:
  - name: app
    image: jc21/nginx-proxy-manager:latest
    ports:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
    - containerPort: 81
      hostPort: 81
      protocol: TCP
    volumeMounts:
    - name: data-volume
      mountPath: /data
    - name: letsencrypt-volume
      mountPath: /etc/letsencrypt
  volumes:
  - name: data-volume
    configMap:
      name: data-volume
  - name: letsencrypt-volume
    configMap:
      name: letsencrypt-volume